sudo: required
services:
  - docker

before_install:
  - docker build -t leo/docker-react -f Dockerfile.dev .

# Comandi da eseguire per far partire i test, -e CI=true per uscire dalla CLI creata da npm run test
script:
  - docker run -e CI=true leo/docker-react