name: Deploy React App
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - use: actions/checkout@v2
      - run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - run: docker build -t leo/frontendreact -f Dockerfile.dev
      - run: docker run -e CI=true leo/frontendreact npm run test